services:
  # custom image
  app:
    build:
      args:
        user: brunomelodev
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: brunomelodev/laravel-app
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    restart: always
    depends_on:
      - redis
      - queue
    networks:
      - laravel-network

  #nginx
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel-network

  # db
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - laravel-network

  # redis
  redis:
    image: redis:latest
    networks:
      - laravel-network

  # queue
  queue:
    build:
      args:
        user: brunomelodev
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    restart: always
    command: "php artisan queue:work"
    volumes:
      - ./:/var/www
    depends_on:
      - redis
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
